sources:
  - name: Chain
    handler:
      graphql:
        endpoint: http://chain-graphql:3001/graphql
  - name: Contracts
    handler:
      graphql:
        endpoint: http://contracts-graphql:3002/graphql

additionalEnvelopPlugins: './envelop-plugins'

serve:
  hostname: graphql-gateway
  port: 3000
  playground: true
  cors:
    origin: '*'

additionalTypeDefs: ./additional-types/additional-types.graphql
additionalResolvers:
  # Chain
  - !include ./resolvers/chain/address-block-producers.yaml
  - !include ./resolvers/chain/address-block-rewards.yaml
  - !include ./resolvers/chain/address-token-balances.yaml
  - !include ./resolvers/chain/address-token-operations.yaml
  - !include ./resolvers/chain/block-reward.yaml
  - !include ./resolvers/chain/operation-contract-operation.yaml
  - !include ./resolvers/chain/operation-contract-operation-union.yaml
  - !include ./resolvers/chain/system-call-operation-contract.yaml
  - !include ./resolvers/chain/system-contract-operation-contract.yaml
  - !include ./resolvers/chain/upload-contract-operation-contract.yaml
    # Contracts
  - !include ./resolvers/contracts/block-producer-address.yaml
  - !include ./resolvers/contracts/block-reward-burner.yaml
  - !include ./resolvers/contracts/contract-operation-contract.yaml
