sources:
  - name: Chain
    handler:
      graphql:
        endpoint: http://chain-graphql:3001/graphql
  - name: Contracts
    handler:
      graphql:
        endpoint: http://contracts-graphql:3002/graphql

additionalEnvelopPlugins: './envelop-plugins'

serve:
  hostname: graphql-gateway
  port: 3000
  playground: true
  cors:
    origin: '*'

additionalTypeDefs:
  !include ./additional-types/additional-types.yaml
additionalResolvers:
  # Chain
  - !include ./resolvers/chain/address-rewards.yaml
  - !include ./resolvers/chain/address-token-balances.yaml
  - !include ./resolvers/chain/address-token-operations.yaml
  - !include ./resolvers/chain/block-reward.yaml
    # Contracts
  - !include ./resolvers/contracts/block-reward-producer.yaml
