sources:
  - name: Chain
    handler:
      graphql:
        endpoint: http://chain-graphql:3001/graphql
  - name: Contracts
    handler:
      graphql:
        endpoint: http://contracts-graphql:3002/graphql

additionalEnvelopPlugins: './envelop-plugins'

serve:
  hostname: graphql-gateway
  port: 3000
  playground: true
  cors:
    origin: '*'
