apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: jsonrpc-data
  name: jsonrpc-data
  namespace: koiner-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
