apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: koiner-graphql-gateway
  name: koiner-graphql-gateway
  namespace: koiner-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: koiner-graphql-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: koiner-graphql-gateway
    spec:
      containers:
        - name: koiner-graphql-gateway
          image: elimbatido/koiner-graphql-gateway:v0.2.5
#          envFrom:
#            - configMapRef:
#                name: gateway-config
          env:
            - name: CHAIN_GRAPHQL_URL
              value: "http://chain/graphql"
            - name: CONTRACTS_GRAPHQL_URL
              value: "http://contracts/graphql"
            - name: NETWORK_GRAPHQL_URL
              value: "http://network/graphql"
            - name: TOKENIZE_GRAPHQL_URL
              value: "http://tokenize/graphql"
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "250m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
          ports:
            - containerPort: 3000
#          readinessProbe:
#            tcpSocket:
#              port: 3000
#            initialDelaySeconds: 5
#            periodSeconds: 5
#          livenessProbe:
#            httpGet:
#              path: /healthcheck
#              port: 3000
          imagePullPolicy: Always
      serviceAccountName: default
