apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: koiner-tokenize-graphql
  name: koiner-tokenize-graphql
  namespace: koiner-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: koiner-tokenize-graphql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: koiner-tokenize-graphql
    spec:
      containers:
        - name: koiner-tokenize-graphql
          image: elimbatido/koiner-tokenize-graphql:v0.2.13
          envFrom:
            - configMapRef:
                name: graphql-config
            - configMapRef:
                name: tokenize-graphql-config
            - secretRef:
                name: db-tokenize-credentials
            - secretRef:
                name: amqp-credentials
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "250m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
          ports:
            - containerPort: 3004
          readinessProbe:
            tcpSocket:
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
          imagePullPolicy: Always
      serviceAccountName: default
