apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: koinos-data
  name: koinos-data
  namespace: koiner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
