serve:
#  hostname: "{env.HOSTNAME}"
  hostname: "graphql-gateway"
  playground: true
#  cors:
#    origin: '*'

sources:
  - name: Chain
    handler:
      graphql:
        endpoint: "{env.CHAIN_GRAPHQL_URL}"
  - name: Contracts
    handler:
      graphql:
        endpoint: "{env.CONTRACTS_GRAPHQL_URL}"

additionalEnvelopPlugins: './envelop-plugins'

additionalTypeDefs: ./additional-types/additional-types.graphql
additionalResolvers:
  # Chain
  - !include ./resolvers/chain/address-block-producers.yaml
  - !include ./resolvers/chain/address-block-rewards.yaml
  - !include ./resolvers/chain/address-token-holders.yaml
  - !include ./resolvers/chain/address-token-operations.yaml
  - !include ./resolvers/chain/block-reward.yaml
  - !include ./resolvers/chain/operation-contract-operation.yaml
  - !include ./resolvers/chain/operation-contract-operation-union.yaml
  - !include ./resolvers/chain/system-call-operation-contract.yaml
  - !include ./resolvers/chain/system-contract-operation-contract.yaml
  - !include ./resolvers/chain/upload-contract-operation-contract.yaml
    # Contracts
  - !include ./resolvers/contracts/block-producer-address.yaml
  - !include ./resolvers/contracts/block-reward-burner.yaml
  - !include ./resolvers/contracts/block-reward-producer-address.yaml
  - !include ./resolvers/contracts/contract-operation-contract.yaml
