serve:
  hostname: '{env.MESH_HOSTNAME}'
  port: '{env.PORT}'
  playground: true
  cors:
    origin: '*'

sources:
  - name: Chain
    handler:
      graphql:
        endpoint: "{env.CHAIN_GRAPHQL_URL}"
        operationHeaders:
          Origin: '{env.MESH_URL}'
          Referer: '{env.MESH_URL}'
  - name: Contracts
    handler:
      graphql:
        endpoint: "{env.CONTRACTS_GRAPHQL_URL}"
        operationHeaders:
          Origin: '{env.MESH_URL}'
          Referer: '{env.MESH_URL}'
  - name: Network
    handler:
      graphql:
        endpoint: "{env.NETWORK_GRAPHQL_URL}"
        operationHeaders:
          Origin: '{env.MESH_URL}'
          Referer: '{env.MESH_URL}'
  - name: Tokenize
    handler:
      graphql:
        endpoint: "{env.TOKENIZE_GRAPHQL_URL}"
        operationHeaders:
          Origin: '{env.MESH_URL}'
          Referer: '{env.MESH_URL}'

additionalEnvelopPlugins: './envelop-plugins'

additionalTypeDefs: ./additional-types/additional-types.graphql
additionalResolvers:
  - !include ./resolvers/koiner-stats-block-production-stats.yaml
  - !include ./resolvers/koiner-stats-koin-stats.yaml
  - !include ./resolvers/koiner-stats-token-stats.yaml
  # Chain
  - !include ./resolvers/chain/address-block-producers.yaml
  - !include ./resolvers/chain/address-block-rewards.yaml
  - !include ./resolvers/chain/address-token-holders.yaml
  - !include ./resolvers/chain/address-token-operations.yaml
  - !include ./resolvers/chain/block-reward.yaml
  - !include ./resolvers/chain/operation-contract-operation.yaml
  - !include ./resolvers/chain/operation-contract-operation-union.yaml
  - !include ./resolvers/chain/system-call-operation-contract.yaml
  - !include ./resolvers/chain/system-contract-operation-contract.yaml
  - !include ./resolvers/chain/upload-contract-operation-contract.yaml
  # Contracts
  - !include ./resolvers/contracts/contract-operation-contract.yaml
  - !include ./resolvers/contracts/contract-operation-transaction.yaml
  # Network
  - !include ./resolvers/network/block-producer-address.yaml
  - !include ./resolvers/network/block-reward-burner.yaml
  - !include ./resolvers/network/block-reward-producer-address.yaml
  # Tokenize
  - !include ./resolvers/tokenize/token-operation-transaction.yaml
