apiVersion: v1
kind: Service
metadata:
  labels:
    service: koiner-tokenize-sync
  name: koiner-tokenize-sync
  namespace: koiner-sync
spec:
  ports:
    - name: "8000"
      protocol: TCP
      port: 8000
      targetPort: 3104
  selector:
    service: koiner-tokenize-sync
