configMapGenerator:
  - name: sync-config
    envs:
      - config/sync.common.properties
  - name: chain-sync-config
    envs:
      - config/chain-sync.common.properties
  - name: contracts-sync-config
    envs:
      - config/contracts-sync.common.properties
  - name: network-sync-config
    envs:
      - config/network-sync.common.properties
  - name: tokenize-sync-config
    envs:
      - config/tokenize-sync.common.properties

resources:
  - koiner-chain-sync-deployment.yaml
  - koiner-chain-sync-service.yaml
  - koiner-contracts-sync-deployment.yaml
  - koiner-contracts-sync-service.yaml
  - koiner-network-sync-deployment.yaml
  - koiner-network-sync-service.yaml
  - koiner-tokenize-sync-deployment.yaml
  - koiner-tokenize-sync-service.yaml
  - ingress.yaml
