namespace: koinos

resources:
  - namespace.yaml
  - ../../base

secretGenerator:
  - name: monitor-credentials
    envs:
      - env/.env.monitor
    namespace: koinos

configMapGenerator:
  - name: koinos-config
    files:
      - config/koinos-config.yaml
