apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: koinos-data10
  name: koinos-data10
  namespace: koinos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
