namespace: koiner-sync

resources:
  - namespace.yaml
  - ../../../base/sync

secretGenerator:
  - name: db-chain-credentials
    envs:
      - env/.env.db-chain
    namespace: koiner-sync
  - name: db-contracts-credentials
    envs:
      - env/.env.db-contracts
    namespace: koiner-sync
  - name: db-network-credentials
    envs:
      - env/.env.db-network
    namespace: koiner-sync
  - name: db-tokenize-credentials
    envs:
      - env/.env.db-tokenize
    namespace: koiner-sync
  - name: amqp-credentials
    envs:
      - env/.env.amqp
    namespace: koiner-sync
  - name: redis-credentials
    envs:
      - env/.env.redis
    namespace: koiner-sync
  - name: sync-credentials
    envs:
      - env/.env.sync
    namespace: koiner-sync

configMapGenerator:
  - name: sync-config
    behavior: merge
    envs:
      - config/sync.properties
  - name: chain-sync-config
    behavior: merge
    envs:
      - config/chain-sync.properties
  - name: contracts-sync-config
    behavior: merge
    envs:
      - config/contracts-sync.properties
  - name: network-sync-config
    behavior: merge
    envs:
      - config/network-sync.properties
  - name: tokenize-sync-config
    behavior: merge
    envs:
      - config/tokenize-sync.properties
